# Generated by Django 4.2.7 on 2024-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_gym_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='notes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
