# Generated by Django 4.2.7 on 2024-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goaltracker', '0002_alter_goal_date_completed_alter_goal_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notes',
            field=models.JSONField(default={}, null=True),
        ),
    ]
