# Generated by Django 4.2.7 on 2024-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goaltracker', '0003_alter_goal_date_start_alter_goal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='notes',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
