# Generated by Django 4.2.7 on 2024-01-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0002_alter_dietplan_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietplan.predefineddietplan'),
        ),
    ]
